use_default_settings: true

general:
  instance_name: "Local-AI-Search"

search:
  formats:
    - html
    - json

server:
  secret_key: "local-ai-searxng-2026-07-07-change-me-9f3c2a71"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

redis:
  url: false
